### ISSUE TITLE
Animation doesn't play when list is refreshed with StreamBuilder

### ISSUE THREAD

**Issue by Gintasz** [mobiten/flutter_staggered_animations#13]
If I wrap ListView with staggeredList animation from the example code inside StreamBuilder, animation plays on the first run, but does not play when stream builder calls the builder a 2nd time.

**Comment by MrLepage** [comment]
Hello, 
You can try to add a `UniqueKey()` as a key to the AnimationLimiter

**Comment by Gintasz** [comment]
I tried placing AnimationLimiter as 1st parent of ListView and also as a parent of StreamBuilder. With either of these tries, animation does seem to play when list is refreshed, but then it glitches. See attached video file.

[1111.mov.zip](https://github.com/mobiten/flutter_staggered_animations/files/4402208/1111.mov.zip)

**Comment by Gintasz** [comment]
And then I'm also getting this

```

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
setState() called after dispose(): _AnimationLimiterState#40c11(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
#2      _AnimationLimiterState.initState.<anonymous closure> (package:flutter_staggered_animations/src/animation_limiter.dart:45:7)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
setState() called after dispose(): _AnimationLimiterState#46820(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by MrLepage** [comment]
@Gintasz 
The `UniqueKey()` make the AnimationLimiter be recreated each time your widget is rebuilt.

Depending on your use case, you probably need to update this key only on the first build when you want your list animation to play. 

One way of doing this is to pass a boolean to you cell like `animate` and only wrap your cell in Animations widget if you need to `animate`.

**Comment by Gintasz** [comment]
Looks like LayoutBuilder as parent in the tree of my widgets is at fault, as it's called every time list is scrolled. Yet to figure out why. Animation works fine if it's removed.
